### ISSUE TITLE
FYI - script update hangs/crashes kodi (.41)

### ISSUE THREAD

**Issue by mgonzales71** [marcelveldt/script.skin.helper.service#22]
just got pushed and update of the script that hung (or crashed) kodi

these are the messages in log file up until app hung:

04:52:18 T:7192  NOTICE: Thread BackgroundLoader start, auto delete: false
04:53:37 T:4056   ERROR: CPythonInvoker(3, C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\service.py): script didn't stop in 5 seconds - let's kill it
04:53:51 T:9988  NOTICE: Thread LanguageInvoker start, auto delete: false
04:53:52 T:2264  NOTICE: Thread BackgroundLoader start, auto delete: false
04:53:53 T:7476   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SystemExit'>
                                            Error Contents: <NULL>
                                            Traceback (most recent call last):
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\KodiMonitor.py", line 48, in onNotification
                                                logMsg("Kodi_Monitor: sender %s - method: %s  - data: %s"%(sender,method,data))
                                            SystemExit
                                            -->End of Python script error report<--
04:53:53 T:7124  NOTICE: -->Python Interpreter Initialized<--
04:53:57 T:952   ERROR: C:\Users\Mario\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
04:53:57 T:7476  NOTICE: SKIN HELPER SERVICE --> shutdown requested !
04:53:57 T:7476  NOTICE: Skin Helper Service --> BackgroundsUpdater - stop called
04:53:57 T:9556  NOTICE: -->Python Interpreter Initialized<--
04:53:57 T:7476  NOTICE: Previous line repeats 3 times.
04:53:57 T:7476  NOTICE: Skin Helper Service --> HomeMonitor - stop called
04:54:02 T:9988  NOTICE: skin helper service version 0.0.41 started
04:54:02 T:8356  NOTICE: ----------------------------------------
04:54:02 T:8356  NOTICE: Exception happened during processing of request from
04:54:02 T:8356  NOTICE: ('127.0.0.1', 55139)
04:54:02 T:8356   ERROR: Traceback (most recent call last):
04:54:02 T:8356   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\SocketServer.py", line 295, in _handle_request_noblock
04:54:02 T:8356   ERROR:     self.process_request(request, client_address)
04:54:02 T:8356   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\SocketServer.py", line 321, in process_request
04:54:02 T:8356   ERROR:     self.finish_request(request, client_address)
04:54:02 T:8356   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\SocketServer.py", line 334, in finish_request
04:54:02 T:8356   ERROR:     self.RequestHandlerClass(request, client_address, self)
04:54:02 T:8356   ERROR:   File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\WebService.py", line 63, in __init__
04:54:02 T:8356   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\SocketServer.py", line 648, in **init**
04:54:02 T:8356   ERROR:     self.server = server
04:54:02 T:8356   ERROR: SystemExit
04:54:02 T:8356  NOTICE: ----------------------------------------
04:54:02 T:7476   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'httplib.BadStatusLine'>
                                            Error Contents: ''
                                            Traceback (most recent call last):
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\service.py", line 46, in <module>
                                                Main()
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\service.py", line 43, in **init**
                                                webService.stop()
                                              File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\WebService.py", line 29, in stop
                                                logMsg("WebService - stop called")
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\httplib.py", line 1067, in getresponse
                                                response.begin()
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\httplib.py", line 409, in begin
                                                version, status, reason = self._read_status()
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\httplib.py", line 373, in _read_status
                                                raise BadStatusLine(line)
                                            BadStatusLine: ''
                                            -->End of Python script error report<--
04:54:05 T:6028  NOTICE: script.tv.show.next.aired: ### TV Show - Next Aired starting GUI proc (6.0.14)
04:54:06 T:11068  NOTICE: Previous line repeats 1 times.
04:54:06 T:11068  NOTICE: Skin Helper Service --> ERROR in BackgroundsUpdater ! --> cannot identify image file
04:54:06 T:11068   ERROR: Traceback (most recent call last):
04:54:06 T:11068   ERROR:   File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\BackgroundsUpdater.py", line 61, in run
04:54:06 T:11068   ERROR:     self.UpdateBackgrounds()
04:54:06 T:11068   ERROR:   File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\BackgroundsUpdater.py", line 429, in UpdateBackgrounds
04:54:06 T:11068   ERROR:     self.setWallImageFromPath("SkinHelper.AllMusicSongsBackground.Wall","musicdb://songs/",True)
04:54:06 T:11068   ERROR:   File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\BackgroundsUpdater.py", line 167, in setWallImageFromPath
04:54:06 T:11068   ERROR:     images = createImageWall(self.allBackgrounds[libPath],windowProp,blackWhite,square)
04:54:06 T:11068   ERROR:   File "C:\Users\Mario\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\ImageWall.py", line 56, in createImageWall
04:54:06 T:11068   ERROR:     img = Image.open(img_obj)
04:54:06 T:11068   ERROR:   File "C:\Program Files (x86)\Kodi\addons\script.module.pil\lib\PIL\Image.py", line 1980, in open
04:54:06 T:11068   ERROR:     raise IOError("cannot identify image file")
04:54:06 T:11068   ERROR: IOError: cannot identify image file
04:54:06 T:11068   ERROR: XFILE::CDirectory::GetDirectory - Error getting
04:54:16 T:8204  NOTICE: Thread LanguageInvoker start, auto delete: false
04:54:16 T:8204  NOTICE: -->Python Interpreter Initialized<--
04:54:18 T:8608  NOTICE: Thread LanguageInvoker start, auto delete: false
04:54:18 T:8608  NOTICE: -->Python Interpreter Initialized<--

**Comment by mgonzales71** [comment]
oh and in titan.beta you have an unbalance in the force :smile:

05:08:25 T:9504   ERROR: unmatched parentheses in )

**Comment by marcelveldt** [comment]
Error in skinhelper should be fixed in latest version, please test if you want.

About the unmatched parenthese error... That is going to be a pain to find. I will have to dig through all latest commits to see if I can spot the error. Somewehere among these lines there will be a ) too many :-)

**Comment by mgonzales71** [comment]
could this be it?
line 438 of IncludesViews.xml

```
                <visible>[Container.Content(TVShows) | Container.Content(episodes) | Container.Content(sets) | StringCompare(Container.Folderpath,videodb://movies/sets/)] + !IsEmpty(ListItem.Premiered)</visible>
```

its missing a ] at the end - so maybe not the ) in question but I will see what else I come across :-)

**Comment by mgonzales71** [comment]
around line 795 of the same file something looks off here too but I can't be for certain... hehe

maybe I have been staring at code too long today trying to find this pesky unbalanced ( lol

**Comment by mgonzales71** [comment]
ok last one for now - i have a headache lol 

line 436 of IncludesVariables.xml looks off :-)

hehe - hope you are having a good weekend Marcel!

Mario

**Comment by mgonzales71** [comment]
finally - I grabbed git copy of helper and still getting the same image errors.  doesn't seem to cause any issues in the GUI itself like crashes/hangs or notification "bombs" it could be a corrupt image file I have but not sure how to find out which one - maybe you can log file name/path to narrow down cause?

**Comment by marcelveldt** [comment]
Fix is on Git for the helper service

**Comment by marcelveldt** [comment]
Thanks for trying to find the parenthese error. Unfortunately none of these lines contained the error.
I will dig further to try find this error.

**Comment by marcelveldt** [comment]
Finally found it. Will be fixed in next beta (and on Git) later today
