### ISSUE TITLE
Next Aired Doesn't Work

### ISSUE THREAD

**Issue by MrsAngelD** [marcelveldt/script.skin.helper.service#94]
So the Next aired widget doesn't seem to work here is some info from my log. I've tried both the kodi repo version and the version from  your repo. neither works. Also I can't get a list of my PVR channels to show up.

`15:35:04.692 T:15384 WARNING: Skin Helper Widgets --> Traceback (most recent call last):
                                              File "C:\Users\Angel\AppData\Roaming\Kodi\addons\script.skin.helper.widgets\resources\lib\main.py", line 142, in show_widget_listing
                                                all_items = getattr(media_class, action)()
                                              File "C:\Users\Angel\AppData\Roaming\Kodi\addons\script.skin.helper.widgets\resources\lib\episodes.py", line 178, in nextaired
                                                episodes = self.metadatautils.thetvdb.get_kodi_unaired_episodes(True)
                                              File "C:\Users\Angel\AppData\Roaming\Kodi\addons\script.module.thetvdb\lib\thetvdb.py", line 464, in get_kodi_unaired_episodes
                                                episodes = [self.get_nextaired_episode(serieid)]
                                              File "C:\Users\Angel\AppData\Roaming\Kodi\addons\script.module.thetvdb\lib\thetvdb.py", line 332, in get_nextaired_episode
                                                next_episodes = self.get_unaired_episodes(seriesid)
                                              File "C:\Users\Angel\AppData\Roaming\Kodi\addons\script.module.thetvdb\lib\thetvdb.py", line 321, in get_unaired_episodes
                                                episode = self.get_episode(episode["id"], seriesinfo)
                                              File "C:\Users\Angel\AppData\Roaming\Kodi\addons\script.module.simplecache\lib\simplecache.py", line 284, in decorated
                                                result = func(*args, **kwargs)
                                              File "C:\Users\Angel\AppData\Roaming\Kodi\addons\script.module.thetvdb\lib\thetvdb.py", line 146, in get_episode
                                                episode = self.map_episode_data(episode, seriesdetails)
                                              File "C:\Users\Angel\AppData\Roaming\Kodi\addons\script.module.thetvdb\lib\thetvdb.py", line 512, in map_episode_data
                                                result["airday.int"] = seriesdetails["airday.int"]
                                            KeyError: 'airday.int'
15:35:04.692 T:15384   ERROR: Skin Helper Widgets --> Exception in main ! --> 'airday.int'`

**Comment by marcelveldt** [comment]
This should be fixed in the latest version. Can you confirm ?

**Comment by MrsAngelD** [comment]
I just realized I put this issue in the wrong repo, I'm sorry about that apparently the issue is with Skin.helper.widgets. I downloaded the latest versions of both script.skin.helper.service & script.skin.helper.widgets from the repo's and I still can't get anything to load using the Aeon Madnox skin.

here's my most recent error:

`14:20:14.671 T:16032   ERROR: XFILE::CDirectory::GetDirectory - Error getting pvr://channels/tv/all channel/;reload=20170805181953
14:20:15.915 T:6320   ERROR: XFILE::CDirectory::GetDirectory - Error getting
14:20:19.112 T:4364 WARNING: Skin Helper Widgets --> Traceback (most recent call last):
                                              File "C:\Users\Angel\AppData\Roaming\Kodi\addons\script.skin.helper.widgets\resources\lib\main.py", line 142, in show_widget_listing
                                                all_items = getattr(media_class, action)()
                                              File "C:\Users\Angel\AppData\Roaming\Kodi\addons\script.skin.helper.widgets\resources\lib\episodes.py", line 204, in nextaired
                                                episodes = self.metadatautils.thetvdb.get_kodi_unaired_episodes(True)
                                              File "C:\Users\Angel\AppData\Roaming\Kodi\addons\script.module.thetvdb\lib\thetvdb.py", line 437, in get_kodi_unaired_episodes
                                                kodi_series = self.get_kodishows(True)
                                              File "C:\Users\Angel\AppData\Roaming\Kodi\addons\script.module.thetvdb\lib\thetvdb.py", line 373, in get_kodishows
                                                if not continuing_only or (continuing_only and tvdb_details["status"] == "Continuing"):
                                            KeyError: 'status'
14:20:19.112 T:4364   ERROR: Skin Helper Widgets --> Exception in main ! --> 'status'
14:20:39.737 T:13716   ERROR: XFILE::CFile::Delete - Error deleting file C:\Users\Angel\AppData\Roaming\Kodi\userdata\Thumbnails\e\eb02b9ab.jpg
14:20:39.737 T:13716   ERROR: XFILE::CFile::Delete - Error deleting file special://thumbnails/e/eb02b9ab.jpg`

**Comment by marcelveldt** [comment]
Strange, this error should not be possible at all. Anyways, I've just added in an additional check to prevent this from happening. There will be an update of script.module.thetvdb (version 1.0.23) available on my repo within an hour or so. Please test again after it updated and let me know.
